### ISSUE TITLE
Package constraints

### ISSUE THREAD

**Issue by ouya99** [drew-y/meteor-autoform-datetimepicker#4]
I am using autoform4.2 due to a constraint from meteoric:autoform-ionic.

Could you add support for lower versions or am I doing something wrong here?

=> Errors prevented startup:
While selecting package versions:
   error: Conflict: Constraint aldeed:autoform@5.1.2 is not satisfied by aldeed:autoform 4.2.2.
   Constraints on package "aldeed:autoform":
- aldeed:autoform@4.2.0 <- meteoric:autoform-ionic 0.1.5
- aldeed:autoform@4.0.0 || 5.0.0 <- elevatedevdesign:autoform-nouislider 0.1.0
- aldeed:autoform@4.0.0 || 5.0.0 <- abdj:autoform-google-places-input 0.0.5
- aldeed:autoform@5.1.2 <- drewy:autoform-datetimepicker 1.0.666666

**Comment by drew-y** [comment]
I'll see what I can do. It's probably just a matter of changing the auto
form version constraint in package.js but there could be some compatibility
issues. I'm not currently near my computer though so you may just want to
for this repo and submit a pull request in the mean time.

**Comment by ouya99** [comment]
I found a possible solution here

https://github.com/meteoric/autoform-ionic/issues/14

so maybe thats enough. I will file a report. Thanks for your quick replay!

**Comment by ouya99** [comment]
fixed it with a autoform-ionic upgrade
