### ISSUE TITLE
Cordova?

### ISSUE THREAD

**Issue by ouya99** [drew-y/meteor-autoform-datetimepicker#5]
Is this plugin ready to work and tested with Cordova builds for Android and iOS (various versions?)

**Comment by drew-y** [comment]
This is really more of an issue for the original datetimepicker repo over at https://github.com/xdan/datetimepicker. I haven't personally used Cordova or tested datetimepicker on mobile (my applications using this repo are targeted for desktop sized screens) but I honestly cant imagine datetimepicker being terribly nice on mobile.
