### ISSUE TITLE
Schema.Date or date?

### ISSUE THREAD

**Issue by ouya99** [drew-y/meteor-autoform-datetimepicker#6]
I pasted 

``` javascript
Schema.Date = new SimpleSchema({
  date: {
    type: String,
    autoForm: {
      afFieldInput: {
        type: "datetimepicker",
      }
    }
  }
});
```

from your site
https://github.com/drew-y/meteor-autoform-datetimepicker/

in my definitions and now I am getting an error. 
Could you please add way to add a date field to a scheme. 

Error: Invalid definition for date field.
W20151123-01:03:05.278(1)? (STDERR)     at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1328:1
W20151123-01:03:05.279(1)? (STDERR)     at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
W20151123-01:03:05.279(1)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1325:1)
W20151123-01:03:05.279(1)? (STDERR)     at both/db.js:147:1
W20151123-01:03:05.279(1)? (STDERR)     at both/db.js:322:1

OR
maybe a date field inside the scheme, e.g.

``` javascript
    date: {
      type: "datetimepicker",
      autoForm: {
        afFieldInput: {
          type: "datetimepicker",
        }
      }
    },
```

should do, but then I get

Error: Invalid definition for date field.
W20151123-01:07:26.121(1)? (STDERR)     at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1328:1
W20151123-01:07:26.122(1)? (STDERR)     at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
W20151123-01:07:26.122(1)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1325:1)
W20151123-01:07:26.122(1)? (STDERR)     at both/db.js:158:1
W20151123-01:07:26.122(1)? (STDERR)     at both/db.js:327:1

**Comment by drew-y** [comment]
Hmmm

``` javascript
Schema.Date = new SimpleSchema({
  date: {
    type: String,
    autoForm: {
      afFieldInput: {
        type: "datetimepicker",
      }
    }
  }
});
```

Is the correct way of adding this field to the schema. Do you have datetimepicker installed? This is just a wrapper for meteor-autoform. Have you already run the following?

``` shell
meteor add drewy:datetimepicker
```

As for the second question

``` javascript
    date: {
      type: "datetimepicker",
      autoForm: {
        afFieldInput: {
          type: "datetimepicker",
        }
      }
    },
```

Would not work. The "type" field is controlled by the actual autoform repo and must be a recognized javascript datatype. Unfortunately the Date type is not supported at the moment. Id recommend using moment.js to parse the date. It is a dependency of datetimepicker anyway.

**Comment by ouya99** [comment]
Yes the package drewy:datetimepicker is installed.

The Schema.Date is giving me a compile error at line 119, where its first line of code block begins with "Schema.Date = new SimpleSchema" .

Think it is more about "redefining Schema.Date or maybe a keyword "Date" ? It does not complain about the datetimepicker here.

output:

W20151124-00:30:25.543(1)? (STDERR) /Users/alexander/.meteor/packages/meteor-tool/.1.1.10.ax6hcb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151124-00:30:25.543(1)? (STDERR)                         throw(ex);
W20151124-00:30:25.543(1)? (STDERR)                               ^
W20151124-00:30:25.543(1)? (STDERR) Error: Invalid definition for date field.
W20151124-00:30:25.544(1)? (STDERR)     at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1328:1
W20151124-00:30:25.544(1)? (STDERR)     at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
W20151124-00:30:25.544(1)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1325:1)
W20151124-00:30:25.544(1)? (STDERR)     at both/db.js:119:1
W20151124-00:30:25.544(1)? (STDERR)     at both/db.js:330:1

**Comment by drew-y** [comment]
Can you show me the definition for your date field?

**Comment by ouya99** [comment]
Just this Schema.... Do you mean where I reference it in my schema? or the autoform html?

Schema.Date = new SimpleSchema({
  date: {
    type: String,
    autoForm: {
      afFieldInput: {
        type: "datetimepicker",
      }
    }
  }
});

thought about using at in another Schema like this

```
date: {
  type: Schema.Address,
},
```

**Comment by drew-y** [comment]
Sorry, the autoform html.

**Comment by ouya99** [comment]
{{#autoForm id='_listsNew' schema=Schema.Markers collection='Markers' type='insert'}}
    {{> afQuickField name='date' type='datetimepicker' opts=pickerOpts}}
    <button type="submit">Submit</button>
  {{/autoForm}}

```
<button type="submit">Submit</button> is correct - github formating removed this code line
```

**Comment by drew-y** [comment]
Ah. This could be you're problem. You do not need to define

``` javascript
afFieldInput: {
    type: "datetimepicker",
}
```

if you set the type manually in the html. Try taking out the afFieldInput object out of your schema.

**Comment by ouya99** [comment]
Cut it down to

Schema.Date = new SimpleSchema({
  date: {
    type: String
  }
});

Great it works! Now I am using

  {{> afQuickField name='date' type='datetimepicker' opts=pickerOpts}}

Still trying to figure out how to build the schema when using this autoform statement. Could you shed a bit more light on this please

**Comment by ouya99** [comment]
{{> afQuickField name='date' type='datetimepicker' opts=pickerOpts}}

is even working without the field 'date' defined in my Schema. That is odd. Maybe then it was defined twice so thats why it complained. 
Would it then work with inserting and saving a value into the correction collection, cause it seems to be referencing Schema.Date's date field instead of my Schema.Markers date field

**Comment by drew-y** [comment]
Awesome! Glad I could help. I believe you'll need have the date field defined in the schema if you plan on using SimpleSchema/collection2 for validation. 

> Still trying to figure out how to build the schema when using this autoform statement. Could you shed a bit more light on this please

``` javascript
Schema.Date = new SimpleSchema({
  date: {
    type: String
  }
});
```

Is the correct way to define the schema :) If you don't want to specify `type='datetimepicker` in your html then you'd ad

``` javascript
afFieldInput: {
    type: "datetimepicker",
}
```

to your date field in the schema. I'm going to go ahead and close this issue.

**Comment by ouya99** [comment]
Is the correct way to define the schema :) If you don't want to specify type='datetimepicker in your html then you'd ad

afFieldInput: {
    type: "datetimepicker",
}

Yet this reversed approach does not work here. It just would not compile my Schema.Date 

I plan to put this date object into my collection "markers". Now it says "Date must be an object" when submitting. Maybe because it sees a String and expect Schema.Date (an object)?

**Comment by ouya99** [comment]
Finally

```
date: {
  type: Date,
  defaultValue: new Date()
},
```

and

```
{{> afQuickField name='date' type='datetimepicker' opts=pickerOpts}}
```

does allow to enter and submit a value here.

without defining Schema.Date !
