### ISSUE TITLE
Conflict with anti:modals

### ISSUE THREAD

**Issue by ricardo37** [drew-y/meteor-autoform-datetimepicker#7]
Everything works fine in a standard autoform. But when the autoform is inside a template opened via a javascript call to AntiModals.overlay(), the calendar popup displays BEHIND the modal (it's still there if you close the modal), making it unavailable for use in the modal form.

**Comment by ricardo37** [comment]
Simple solution. drewy:datetimepicker uses a z-index of 9999 and anti:modals one of 65536. Just had to bump the former up a bit. It would be nice to have the z-index raised in the official datetimepicker package, so I don't have to make this change manually whenever an update comes along.

**Comment by drew-y** [comment]
Thanks for the solution! This seems like it is more of an issue with the original datetimepicker. drewy:datetimepicker is just a wrapper for meteor. If you submit a pull request/issue with git@github.com:xdan/datetimepicker.git I'll merge it in with the wrapper.
