### ISSUE TITLE
setting locales for datetimepicker ?

### ISSUE THREAD

**Issue by abate** [drew-y/meteor-autoform-datetimepicker#8]
Hello,

How can I change/set the local language for the dtpicker ?
I've tried to put this in the  onRendered call

    $(this.firstNode).setLocale(Meteor.user().profile.language)

but it does not work.

I've also tried to do it globally with the same result ...

    $.datetimepicker.setLocale(Meteor.user().profile.language)
    jQuery.datetimepicker.setLocale(Meteor.user().profile.language)

I can set the language in the options : 

    lang: 'fr' 

but lang does not accept a function and I cannot make this reactive like

    lang: () -> Meteor.user().profile.language

help :)

**Comment by drew-y** [comment]
It looks like I just need to update the linked datetimepicker code to the most recent version. I haven't used this repo in awhile so it hasn't been updated.

**Comment by drew-y** [comment]
That being said this is technically the wrong repo, as this is just a wrapper around datetimepicker for autoform and doesn't itself include datetimepicker. The repo you are looking for (that needs to be updated) is [this one](https://github.com/drew-y/meteor-datetimepicker). A quick and easy fix for you though (without having to wait for me to update the repo) would be to just link the source to the [original datetimepicker](https://github.com/xdan/datetimepicker) somewhere in your index.html file.
